repos:
  - repo: local
    hooks:

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 .
        language: system
        types: [python]
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: bash -c "cd global-server && pytest -v -W ignore::DeprecationWarning"
        language: system
        types: [python]
        pass_filenames: false
