[tool.poetry]
name = "restaraunt-petproject"
version = "0.1.0"
description = ""
authors = ["Vchslv-Zkhrv <vchslv.zkrhv@gmail.com>"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
psycopg2-binary = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
